#!/bin/bash

# Full system upgrade and install core packages.

# Verified on:
# Ubuntu 20.04

# Usage:
# overcast run myInstanceOrCluster install/core

# set -x

if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root." 1>&2
   exit 1
fi

# Install core packages

# Update the package list
apt-get update

# Upgrade all installed packages
# --force-confdef tells dpkg to use the default action
# --force-confold tells it to keep the current version of a configuration file if one has been modified
DEBIAN_FRONTEND=noninteractive apt-get upgrade -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold"

# Ref: https://askubuntu.com/a/340846
echo iptables-persistent iptables-persistent/autosave_v4 boolean true | sudo debconf-set-selections
echo iptables-persistent iptables-persistent/autosave_v6 boolean true | sudo debconf-set-selections

apt-get install -y git-core wget less build-essential iptables-persistent

exit 0
