#!/bin/bash

# Full system upgrade and install core packages.

# Tested on:
# Debian 7.0
# Ubuntu 12.04
# Ubuntu 14.04

# Usage:
# overcast run myInstanceOrCluster install/core

# set -x

if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root." 1>&2
   exit 1
fi

# Install core packages

apt-get update
apt-get install aptitude
aptitude -y full-upgrade
aptitude -y install git-core wget less build-essential iptables-persistent

exit 0
