#!/bin/bash

# Install core packages on Ubuntu 12.04.

# Usage:
# overcast run myInstanceOrCluster install/core

# set -x

if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root." 1>&2
   exit 1
fi

# Install core packages

apt-get update
apt-get install aptitude
aptitude -y full-upgrade
aptitude -y install git-core wget emacs vim less build-essential iptables-persistent
