#!/bin/bash

# Install Docker.

# Tested on:
# Debian 7.0
# Ubuntu 12.04
# Ubuntu 14.04

# Usage:
# overcast run myInstanceOrCluster install/docker

# set -x

if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root." 1>&2
   exit 1
fi

wget -qO- https://get.docker.io/ | sh

exit 0
