#!/bin/bash

# Install Docker on Ubuntu 12.04.

# Usage:
# overcast run myInstanceOrCluster install/docker

# set -x

if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root." 1>&2
   exit 1
fi

wget -qO- https://get.docker.io/ | sh
