#!/bin/bash

# Install ImageMagick.

# Tested on:
# Ubuntu 14.04

# Usage:
# overcast run myInstanceOrCluster install/imagemagick

# set -x

if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root." 1>&2
   exit 1
fi

aptitude -y install imagemagick

exit 0
