#!/bin/bash

# Configure iptables.

# Tested on:
# Debian 7.0
# Ubuntu 12.04
# Ubuntu 14.04

# Usage:
# overcast expose myInstanceOrCluster 22 80 443 3000
# overcast expose myInstanceOrCluster 22 80 443 3000 --whitelist "1.1.1.1 2.2.2.2 192.168.0.0/16"

# set -x

if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root." 1>&2
   exit 1
fi

current_ssh_port=`cat /etc/ssh/sshd_config | grep Port | awk '{ print \$2 }'`

if [ -z "$exposed_ports" ]; then
  echo "No exposed ports defined, no action taken."
  exit 1
fi

ssh_port_not_included=true
for exposed_port in $exposed_ports; do
  if [ "$current_ssh_port" == "$exposed_port" ]; then
    ssh_port_not_included=false
  fi
done

if $ssh_port_not_included; then
  echo "Current SSH port ($current_ssh_port) not included in exposed port list, no action taken."
  exit 1
fi

# Flush all current rules from iptables
iptables -F

for exposed_port in $exposed_ports; do
  port_whitelist_attribute="whitelist_$exposed_port"
  port_whitelist="${!port_whitelist_attribute}"
  if [ -z "$whitelist" ] && [ -z "$port_whitelist" ]; then
    iptables -A INPUT -p tcp --dport $exposed_port -j ACCEPT
  else
    if [ -z "$port_whitelist" ]; then
      for ip in $whitelist; do
        iptables -A INPUT -p tcp -s $ip --dport $exposed_port -j ACCEPT
      done
    else
      for ip in $port_whitelist; do
        iptables -A INPUT -p tcp -s $ip --dport $exposed_port -j ACCEPT
      done
    fi
  fi
done

# Ping
iptables -A INPUT -p icmp -m icmp --icmp-type 8 -j ACCEPT

# Accept packets belonging to established and related connections
iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT

# Localhost
iptables -A INPUT -i lo -j ACCEPT

# Log Dropped Connections
# iptables -A INPUT -m limit --limit 30/minute -j LOG --log-level 7 --log-prefix "Dropped by firewall: "
# iptables -A INPUT -j LOG --log-level 7 --log-prefix "Dropped by firewall: "

# Set default policies for INPUT, FORWARD and OUTPUT chains
iptables -P INPUT DROP
iptables -P FORWARD DROP
iptables -P OUTPUT ACCEPT

# List rules
iptables -L -v

mkdir -p /etc/iptables
iptables-save > /etc/iptables/rules.v4

exit 0
