#!/bin/bash

# Install MySQL on Ubuntu 12.04.

# Usage:
# overcast run myInstanceOrCluster install/mysql

# set -x

if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root." 1>&2
   exit 1
fi

DEBIAN_FRONTEND=noninteractive aptitude -q -y install mysql-server libmysqld-dev
