#!/bin/bash

# Install Nginx.

# Tested on:
# Debian 7.0
# Ubuntu 12.04
# Ubuntu 14.04

# Usage:
# overcast run myInstanceOrCluster install/nginx

# set -x

if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root." 1>&2
   exit 1
fi

aptitude install -y nginx

exit 0
