#!/bin/bash

# Install Nginx.

# Verified on:
# Ubuntu 20.04
# Ubuntu 14.04
# Ubuntu 12.04
# Debian 7.0

# Usage:
# overcast run myInstanceOrCluster install/nginx

# set -x

if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root." 1>&2
   exit 1
fi

aptitude install -y nginx

exit 0
