#!/bin/bash

# Install Node LTS
# https://github.com/joyent/node/wiki/Installing-Node.js-via-package-manager

# Verified on:
# Ubuntu 20.04

# Usage:
# overcast run myInstanceOrCluster install/nodejs

# set -x

if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root." 1>&2
   exit 1
fi

curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
apt-get install -y nodejs

exit 0
