#!/bin/bash

# Install Postgres

# Verified on:
# Ubuntu 24.04

# Usage:
# overcast run myInstanceOrCluster install/postgres

set -ex

if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root." 1>&2
   exit 1
fi

# Ref: https://www.digitalocean.com/community/tutorials/how-to-install-postgresql-on-ubuntu-22-04
apt-get update
apt-get install -y postgresql postgresql-contrib
systemctl start postgresql.service
systemctl enable postgresql.service
