#!/bin/bash

# Install Postgres

# Verified on:
# Ubuntu 20.04

# Usage:
# overcast run myInstanceOrCluster install/postgres

set -x

if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root." 1>&2
   exit 1
fi

# Ref: https://www.digitalocean.com/community/tutorials/how-to-install-postgresql-on-ubuntu-20-04-quickstart
apt-get install -y postgresql postgresql-contrib
systemctl start postgresql.service
