#!/bin/bash

# Configure chrooted SFTP.

# Tested on:
# Debian 7.0
# Ubuntu 12.04

# Once configured, users requiring SFTP access must be added to the "sftp" group, like so:
# $ useradd -d /home/myusername -p password myusername
# $ usermod -G sftp myusername
# That user then has SFTP access and is chrooted to their home directory.

# Usage:
# overcast run myInstanceOrCluster install/sftp

# set -x

if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root." 1>&2
   exit 1
fi

groupadd -f sftp

sed -i "s/^Subsystem sftp \/usr\/lib\/openssh\/sftp\-server/# Subsystem sftp \/usr\/lib\/openssh\/sftp-server/g" /etc/ssh/sshd_config

if ! grep -q 'Subsystem sftp internal-sftp' /etc/ssh/sshd_config; then
  cat >> /etc/ssh/sshd_config << EOF

Subsystem sftp internal-sftp

Match group sftp
  ChrootDirectory %h
  X11Forwarding no
  AllowTcpForwarding no
  ForceCommand internal-sftp
EOF
fi

exit 0
