#!/bin/bash

# Ubuntu 14.04 LAMP Server Recipe

# Deploy on a DigitalOcean 512mb:
#   overcast digitalocean create lamp-do-01
#   recipes/lamp-server lamp-do-01

###############################################################################

# Configuration:
if [ -z "$1" ]; then
  echo "Usage: recipes/lamp-server [instance]"
  exit 1
fi

instance=$1

###############################################################################

# You shouldn't need to edit anything below.

set -e

echo "Full system upgrade, installing core packages..."
overcast run $instance install/core install/sftp install/apache install/mysql install/php
overcast reboot $instance

echo "Configuring iptables to only expose HTTP, HTTPS and SSH..."
overcast expose $instance 22 80 443

echo "Done!"
