#!/bin/bash

# Basic health statistics

# Tested on:
# Ubuntu 9.10
# Ubuntu 12.04

cpu_load=`cat /proc/loadavg`
disk_space=`df -m / | tail -n 1`
memory_usage=`free -m | grep Mem`
cache_usage=`free -m | grep "buffers/cache"`
swap_usage=`free -m | grep Swap`

echo {

echo \"cpu_load_1min\": \"`echo $cpu_load | awk '{ print $1 }'`\",
echo \"cpu_load_5min\": \"`echo $cpu_load | awk '{ print $2 }'`\",
echo \"cpu_load_15min\": \"`echo $cpu_load | awk '{ print $3 }'`\",

echo \"disk_space_total\": \"`echo $disk_space | awk '{ print $2 }'`\",
echo \"disk_space_used\": \"`echo $disk_space | awk '{ print $3 }'`\",
echo \"disk_space_available\": \"`echo $disk_space | awk '{ print $4 }'`\",
echo \"disk_space_used_percentage\": \"`echo $disk_space | awk '{ print $5 }'`\",

echo \"memory_total\": \"`echo $memory_usage | awk '{ print $2 }'`\",
echo \"memory_used\": \"`echo $memory_usage | awk '{ print $3 }'`\",
echo \"memory_free\": \"`echo $memory_usage | awk '{ print $4 }'`\",

echo \"memory_used_with_cache\": \"`echo $cache_usage | awk '{ print $3 }'`\",
echo \"memory_free_with_cache\": \"`echo $cache_usage | awk '{ print $4 }'`\",

echo \"swap_total\": \"`echo $swap_usage | awk '{ print $2 }'`\",
echo \"swap_used\": \"`echo $swap_usage | awk '{ print $3 }'`\",
echo \"swap_free\": \"`echo $swap_usage | awk '{ print $4 }'`\",

echo \"open_tcp_connections\": \"`wc -l /proc/net/tcp | awk '{ print $1 }'`\",

echo \"rx_bytes\": \"`cat /sys/class/net/eth0/statistics/rx_bytes`\",
echo \"tx_bytes\": \"`cat /sys/class/net/eth0/statistics/tx_bytes`\",

echo \"processes\": [
echo `ps aux | sed '1 d' | sed 's/"//g' | sed 's/\s\s*/ /g' | cut -d' ' -f1,2,3,4,10,11- | sed -e 's/\(.*\)/"\1",/'`
echo \"\"
echo ]

echo }
