#!/bin/bash

# Install a Discourse Docker container on Ubuntu 12.04

# References:
# https://github.com/discourse/discourse/blob/master/docs/INSTALL-digital-ocean.md
# https://github.com/eviltrout/discourse-droplet

# Usage:
# overcast run myInstanceOrCluster install/discourse \
#   --env "discourseHostname=\"$discourseHostname\"" \
#   --env "discourseDevEmails=\"$discourseDevEmails\"" \
#   --env "discourseSMTPAddress=\"$discourseSMTPAddress\"" \
#   --env "discourseSMTPPort=\"$discourseSMTPPort\"" \
#   --env "discourseSMTPUsername=\"$discourseSMTPUsername\"" \
#   --env "discourseSMTPpassword=\"$discourseSMTPpassword\""

# See also:
# recipes/discourse-docker

# set -x

if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root." 1>&2
   exit 1
fi

aptitude install cgroup-lite

mkdir /var/docker
git clone https://github.com/discourse/discourse_docker.git /var/docker
cd /var/docker
cp samples/standalone.yml containers/app.yml

sed -i "s/DISCOURSE_DEVELOPER_EMAILS\: .*/DISCOURSE_DEVELOPER_EMAILS\: \'$discourseDevEmails\'/g" containers/app.yml
sed -i "s/DISCOURSE_HOSTNAME\: .*/DISCOURSE_HOSTNAME\: \'$discourseHostname\'/g" containers/app.yml
sed -i "s/DISCOURSE_SMTP_ADDRESS\: .*/DISCOURSE_SMTP_ADDRESS\: \'$discourseSMTPAddress\'/g" containers/app.yml
sed -i "s/\#\? \?DISCOURSE_SMTP_PORT\: .*/DISCOURSE_SMTP_PORT\: \'$discourseSMTPPort\'/g" containers/app.yml
sed -i "s/\#\? \?DISCOURSE_SMTP_USER_NAME\: .*/DISCOURSE_SMTP_USER_NAME\: \'$discourseSMTPUsername\'/g" containers/app.yml
sed -i "s/\#\? \?DISCOURSE_SMTP_PASSWORD\: .*/DISCOURSE_SMTP_PASSWORD\: \'$discourseSMTPpassword\'/g" containers/app.yml

./launcher bootstrap app

# Running this separately in recipes/discourse.
# ./launcher start app --skip-prereqs
