#!/bin/bash

# Install NodeJS on Ubuntu 12.04.
# https://github.com/joyent/node/wiki/Installing-Node.js-via-package-manager

# set -x

if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root." 1>&2
   exit 1
fi

aptitude -y install python-software-properties
add-apt-repository ppa:chris-lea/node.js
apt-get update
aptitude -y install nodejs
