#!/bin/bash

# Configure chrooted SFTP.
# Tested on Ubuntu 12.04.

# Once configured, users requiring SFTP access must be added to the "sftp" group, like so:
# $ useradd -d /home/myusername -p password myusername
# $ usermod -G sftp myusername
# That user then has SFTP access and is chrooted to their home directory.

set -x

groupadd -f sftp

sed -i"-orig" "s/Subsystem sftp \/usr\/lib\/openssh\/sftp\-server/# Subsystem sftp \/usr\/lib\/openssh\/sftp-server/" /etc/ssh/sshd_config

cat >> /etc/ssh/sshd_config << EOF

Subsystem sftp internal-sftp

Match group sftp
  ChrootDirectory %h
  X11Forwarding no
  AllowTcpForwarding no
  ForceCommand internal-sftp
EOF
