#!/usr/bin/env bash

# Configures SSH to enhance security.
# - Disallows password logins.
# - Decreases LoginGraceTime.
#
# Tested on:
# Ubuntu 22.04, 20.04, 14.04, 12.04
# Debian 7.0

# Usage:
# overcast run myInstanceOrCluster harden_ssh

# set -x

if [ "$(id -u)" != "0" ]; then
  echo "This script must be run as root." 1>&2
  exit 1
fi

cp /etc/ssh/sshd_config "/etc/ssh/sshd_config_backup-$(date +%F-%T)"

sed -i -r 's/^#?(LoginGraceTime)[[:space:]]+[0-9]+m?/\1 30/g' /etc/ssh/sshd_config
sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config

# These are off by default in Ubuntu 20.04, leaving in for backwards compatibility.
sed -i -r 's/#\?PasswordAuthentication yes/PasswordAuthentication no/g' /etc/ssh/sshd_config
sed -i 's/ChallengeResponseAuthentication yes/ChallengeResponseAuthentication no/g' /etc/ssh/sshd_config

# Check the SSH configuration for errors
sshd -t
if [ $? -ne 0 ]; then
   echo "Error in SSH configuration. Not reloading SSH."
   exit 1
fi

# Using `reload` instead of `restart` to avoid killing existing sessions.
service ssh reload

exit 0
