#!/bin/bash

# Basic health statistics

# Tested on:
# Debian 7.0
# Ubuntu 9.10
# Ubuntu 12.04
# Ubuntu 14.04

# Usage:
# overcast health myInstanceOrCluster

cpu_load=`cat /proc/loadavg`
disk_space=`df -m / | tail -n 1`
memory_usage=`free -m | grep Mem`
cache_usage=`free -m | grep "buffers/cache"`
swap_usage=`free -m | grep Swap`
io_usage=`cat /sys/block/xvda/stat 2>/dev/null || cat /sys/block/vda/stat 2>/dev/null || cat /sys/block/sda/stat 2>/dev/null`

echo {

echo \"cpu_1min\": \"`echo $cpu_load | awk '{ print $1 }'`\",
echo \"cpu_5min\": \"`echo $cpu_load | awk '{ print $2 }'`\",
echo \"cpu_15min\": \"`echo $cpu_load | awk '{ print $3 }'`\",

echo \"disk_total\": \"`echo $disk_space | awk '{ print $2 }'`\",
echo \"disk_used\": \"`echo $disk_space | awk '{ print $3 }'`\",
echo \"disk_free\": \"`echo $disk_space | awk '{ print $4 }'`\",

echo \"mem_total\": \"`echo $memory_usage | awk '{ print $2 }'`\",
echo \"mem_used\": \"`echo $memory_usage | awk '{ print $3 }'`\",
echo \"mem_free\": \"`echo $memory_usage | awk '{ print $4 }'`\",

echo \"cache_used\": \"`echo $cache_usage | awk '{ print $3 }'`\",
echo \"cache_free\": \"`echo $cache_usage | awk '{ print $4 }'`\",

echo \"swap_total\": \"`echo $swap_usage | awk '{ print $2 }'`\",
echo \"swap_used\": \"`echo $swap_usage | awk '{ print $3 }'`\",
echo \"swap_free\": \"`echo $swap_usage | awk '{ print $4 }'`\",

echo \"tcp\": \"`wc -l /proc/net/tcp | awk '{ print $1 }'`\",

echo \"rx_bytes\": \"`cat /sys/class/net/eth0/statistics/rx_bytes`\",
echo \"tx_bytes\": \"`cat /sys/class/net/eth0/statistics/tx_bytes`\",

echo \"io_reads\": \"`echo $io_usage | awk '{ print $3 }'`\",
echo \"io_writes\": \"`echo $io_usage | awk '{ print $7 }'`\",

echo \"processes\": [
echo `ps aux | sed '1 d' | sed 's/"//g' | sed 's/\s\s*/ /g' | cut -d' ' -f1,2,3,4,10,11- | sed -e 's/\(.*\)/"\1",/'`
echo \"\"
echo ]

echo }

exit 0
