#!/bin/bash

# List exposed TCP ports.

# Tested on:
# Debian 7.0
# Ubuntu 12.04
# Ubuntu 14.04

# Usage:
# overcast exposed myInstanceOrCluster

if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root." 1>&2
   exit 1
fi

iptables -L -n | grep 'ACCEPT' | grep 'tcp dpt:' | awk '{ print $7 }' | tr -d 'dpt:' | paste -sd ' '

exit 0
